memm_classifiers: one two three four five six seven eight

one:
	python3 learn_memm_worker.py WORKLIST/0
two:
	python3 learn_memm_worker.py WORKLIST/1
three:
	python3 learn_memm_worker.py WORKLIST/2
four:
	python3 learn_memm_worker.py WORKLIST/3
five:
	python3 learn_memm_worker.py WORKLIST/4
six:
	python3 learn_memm_worker.py WORKLIST/5
seven:
	python3 learn_memm_worker.py WORKLIST/6
eight:
	python3 learn_memm_worker.py WORKLIST/7
