test.n.nl 1 :: test 3;beproeving 2;proef 2;proeve 1;
test.n.nl 2 :: test 2;controle 2;controletest 1;controleren 1;keuring 1;onderzoek 1;kwaliteitscontrole 1;
test.n.nl 3 :: experiment 2;test 2;proef 2;raketproef 1;rakettest 1;uitproberen 1;
test.n.nl 4 :: test 3;testen 2;analyse 1;aids test 1;onderzoek 1;aidstest 1;
test.n.nl 5 :: kernproef 3;proef 3;kernwapenproef 2;test 1;
test.n.nl 6 :: bekwaamheidsproef 3;vaardigheidstest 3;bekwaamheidstest 3;test 0;proef 0;
test.n.nl 7 :: testmethode 3;proef 2;methode 2;test 1;testen 1;
test.n.nl 8 :: testverbod 2;kernwapenstop 1;kernproevenstop 1;kernproef 1;kernstop 1;proef 1;kernstopverdrag 1;test 0;
test.n.nl 9 :: proef 3;toetsen 3;confronteren 2;toetsing 1;
test.n.nl 10 :: screeningstest 3;screening 3;opsporingstest 3;test 0;
test.n.nl 11 :: test 2;beproeving 1;vuurproef 1;uitdaging 1;bewijs 1;toetsing 1;proef 1;
test.n.nl 12 :: proef 3;selectieproef 2;test 1;examen 1;preselectie 1;
test.n.nl 13 :: testcase 2;voorbeeldfunctie 2;voorbeeld 2;test 1;test case 1;
test.n.nl 14 :: proef 3;experiment 2;raketproef 1;rakettest 1;oefening 1;test 1;
test.n.nl 15 :: test 3;aidstest 2;testen 2;analyse 1;onderzoek 1;
test.n.nl 16 :: controle 3;dopingcontrole 2;dopingtest 2;test 1;onderzoek 1;
test.n.nl 17 :: kernproef 3;kernwapenproef 3;proef 2;test 1;
test.n.nl 18 :: proefcyclus 3;testcyclus 3;test 2;testen 1;proef 0;
test.n.nl 19 :: controle 2;controleren 1;meting 1;test 1;onderzoek 1;proef 1;testen 1;toetsen 1;
test.n.nl 20 :: kernproef 3;proef 3;kernwapenproef 2;test 1;
test.n.nl 21 :: proef 3;confronteren 3;toetsen 3;
test.n.nl 22 :: testprocedure 2;test 2;testmethode 1;testregime 1;methode 1;onderzoek 1;proef 1;
test.n.nl 23 :: proef 3;dierproef 2;uittesten 1;experiment 1;onderzoek 1;test 1;
test.n.nl 24 :: proef 3;experiment 2;onderzoek 2;test 1;onderzoeken 1;
test.n.nl 25 :: kernproef 3;proef 3;kernwapenproef 2;test 1;
test.n.nl 26 :: lakmoestest 3;lakmoesproef 2;vuurproef 2;proef op de som 1;test 1;proef 0;
test.n.nl 27 :: lakmoesproef 2;vuurproef 2;lakmoestest 2;bewijs 1;testcase 1;test 1;proef 0;
test.n.nl 28 :: bloedonderzoek 3;bloedtest 3;controle 1;test 1;onderzoek 1;
test.n.nl 29 :: test 3;proef 3;onderzoek 2;uitproberen 1;
test.n.nl 30 :: veiligheidstest 3;veiligheidscontrole 3;controle 1;proef 1;test 1;
test.n.nl 31 :: geloofwaardigheidstest 3;keuring 2;test 2;controle 1;toets 1;
test.n.nl 32 :: laboratoriumproef 2;laboratoriumonderzoek 2;laboratoriumtest 2;experiment 1;dierproef 1;proef 1;onderzoek 0;test 0;
test.n.nl 33 :: test 3;controle 2;controleren 1;meting 1;proef 1;testen 1;
test.n.nl 34 :: controle 3;controleren 2;test 1;onderzoek 1;toetsing 1;toetsen 1;
test.n.nl 35 :: DNA-onderzoek 3;DNA-test 3;DNA-proef 3;test 0;onderzoek 0;proef 0;
test.n.nl 36 :: vaardigheidstest 3;bekwaamheidsproef 3;bekwaamheidstest 2;vakbekwaamheidsexamen 1;examen 0;test 0;proef 0;
test.n.nl 37 :: toxiciteitstest 3;toxiciteitsproef 3;test 2;controle 1;proef 0;
test.n.nl 38 :: laboratoriumproef 2;laboratoriumonderzoek 2;laboratoriumtest 2;experiment 1;dierproef 1;proef 1;onderzoek 0;test 0;
test.n.nl 39 :: test 3;onderzoek 2;tuberculinetest 2;controle 1;proef 1;
test.n.nl 40 :: test 3;bloedonderzoek 1;controleren 1;onderzoek 1;controle 1;proef 1;bloedtest 1;
test.n.nl 41 :: experiment 3;proef 3;test 1;dierproef 1;onderzoek 1;
test.n.nl 42 :: kernstopverdrag 3;kernwapenstop 3;kernproevenstop 2;CTBT-Verdrag 1;proef 0;
test.n.nl 43 :: kernproevenstop 2;testverbod 2;kernwapenstop 1;kernstop 1;test 1;proef 1;kernstopverdrag 1;
test.n.nl 44 :: proef 3;testmethode 3;methode 2;proefmethode 1;test 0;
test.n.nl 45 :: beproeving 2;test 2;proefsteen 1;uitdaging 1;ijkpunt 1;probleem 1;proef 0;
test.n.nl 46 :: proeftuin 2;testbank 2;experimenteertuin 1;onderzoek 1;proefbank 1;test 1;experimenteren 0;proef 0;
test.n.nl 47 :: proef 3;testmethode 3;test 1;methode 1;proefmethode 1;
test.n.nl 48 :: testprocedure 2;test 2;keuringsprocedure 1;testprogramma 1;controleren 1;testregime 1;methode 1;keuring 0;
test.n.nl 49 :: proef 3;toetsen 3;test 1;confronteren 1;
test.n.nl 50 :: veiligheidstest 3;veiligheidscontrole 3;controle 2;test 1;
